version: '2'
services:
    ap10-app:
        image: ap10
        external_links:
            - ap10-postgresql:postgresql
            - ap10-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ap10
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    ap10-postgresql:
        extends:
            file: postgresql.yml
            service: ap10-postgresql
    ap10-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ap10-elasticsearch
